= Spring REST Docs
:toc: left
:toclevels: 2
:sectlinks:

[[resources-post]]

[[Login]]
== 회원가입
operation::create-seller[snippets='http-request,request-body,request-fields,response-body,response-fields']
== 회원가입 실패 (이미 가입한 적 있음)
operation::fail-create-seller-already-exists[snippets='http-request,request-body,request-fields,response-body']
== 회원가입 실패 (두 개의 비밀번호가 같지 않음)
operation::fail-create-seller-not-same-password[snippets='http-request,request-body,request-fields,response-body']
== Login
operation::login-success[snippets='http-request,request-body,request-fields,response-body,response-fields']
== 로그인 실패 (회원을 찾을 수 없음)
operation::fail-login-cannot-find-member[snippets='http-request,request-body,request-fields,response-body']
== 로그인 실패 (잘못된 비밀번호)
operation::fail-login-wrong-password[snippets='http-request,request-body,request-fields,response-body']

[[find-id]]
== 아이디 찾기 성공
operation::find-id-success[snippets='http-request,request-body,request-fields,response-body,response-fields']
== 아이디 찾기 실패
operation::fail-find-id[snippets='http-request,request-body,request-fields,response-body']

[[Change-Pwd]]
== 비밀번호 변경
operation::change_pwd_success[snippets='http-request,path-parameters,request-body,request-fields,response-body']
== 비밀번호 변경 실패 (해당 정보 가진 유저 X)
operation::fail_change_pwd_not_found_member[snippets='http-request,request-body,request-fields,response-body']
== 비밀번호 변경 실패 (비밀번호 1, 2 같지 않음)
operation::fail_change_pwd_not_same_password[snippets='http-request,request-body,request-fields,response-body']
== 비밀번호 변경 실패 (이전 비밀번호와 동일)
operation::fail_change_pwd_cannot_use_same_password[snippets='http-request,request-body,request-fields,response-body']

[[Check-LoginId]]
== 아이디 중복 확인 (아이디 생성 가능)
operation::success-check-loginId[snippets='http-request,request-body,request-fields,response-body']
== 아이디 중복 확인 (아이디 이미 존재)
operation::error-find-loginId[snippets='http-request,request-body,request-fields,response-body']

[[Enter]]
== 입점 신청
=== Bearer 토큰 사용하여 로그인 여부 확인 (아래 토큰(Authorization)은 직접 로그인 후 발급받아 사용하여야 함)
operation::success-save-enter[snippets='http-request,request-body,request-fields,response-body,response-fields']
== 입점 신청 실패 (1번 이상 신청)
operation::fail-save-enter-apply-twice[snippets='http-request,request-body,request-fields,response-body']
== 입점 신청 실패 (사장님 찾을 수 없음)
operation::fail-save-enter-cannot-find-member[snippets='http-request,request-body,request-fields,response-body']

[[회원탈퇴]]
== 회원 탈퇴 요청 성공
operation::success-wantDelete[snippets='http-request,path-parameters,response-body']
== 회원 탈퇴 요청 실패 (사장님 id 없을 때)
operation::fail-wantDelete-seller-err[snippets='http-request,path-parameters,response-body']
== 회원 탈퇴 요청 실패 (가게 id 없을 때)
operation::fail-wantDelete-store-err[snippets='http-request,path-parameters,response-body']