= Spring REST Docs
:toc: left
:toclevels: 2
:sectlinks:

[[resources-post]]
== Manager API

[[manager-생성]]
=== Manager 생성 (회원가입)
operation::manager-create[snippets='http-request,request-body,request-fields,response-body,response-fields']

// [[manager-조회]]
// === Manager 조회
// operation::manager-get[snippets='httpie-request,response-body,response-fields']
//
// [[manager-수정]]
// === Manager 수정
// operation::manager-update[snippets='http-request,request-body,request-fields,response-body,response-fields']
//
// [[manager-삭제]]
// === Manager 삭제
// operation::manager-delete[snippets='httpie-request,request-body']

== 가게 관련 API
=== 신규 신청 가게 확인(성공)
operation::success-new-detail[snippets='http-request,response-body,response-fields']

=== 신규 신청 가게 확인(실패 - 신규 신청 매장이 아닌 경우)
operation::fail-new-detail[snippets='http-request,response-body,response-fields']

=== 신규 신청 가게 -> 노출 대기로 변경 (성공)
operation::success-new-to-wait[snippets='http-request,request-body,request-fields,response-body']

=== 신규 신청 가게 -> 노출 대기로 변경 (실패 - isAccepted=false)
operation::fail-new-to-wait[snippets='http-request,request-body,request-fields,response-body']

=== 신규 신청 가게 수정 (성공)
operation::success-update-enter[snippets='http-request,request-body,request-fields,response-body,response-fields']